CREATE TABLE streaks_screener.basketball (
	sofa_match_id int4 NOT NULL,
	dk_match_id int4 NOT NULL,
	league text NULL,
	streak_category text NULL,
	streak_name text NOT NULL,
	streak_value text NULL,
	streak_label text NOT NULL,
	hth_ind bool NOT NULL,
	continued_ind bool NULL,
	home_team text NULL,
	away_team text NULL,
	match_dtime timestamp NULL,
	home_odds int4 NULL,
	away_odds int4 NULL,
	home_half_odds int4 NULL,
	away_half_odds int4 NULL,
	home_qtr_odds int4 NULL,
	away_qtr_odds int4 NULL,
	home_spread numeric NULL,
	home_spread_odds int4 NULL,
	away_spread_odds int4 NULL,
	away_spread numeric NULL,
	total_points_under_odds int4 NULL,
	total_points_line numeric NULL,
	total_points_over_odds int4 NULL,
	CONSTRAINT basketball_pk PRIMARY KEY (sofa_match_id, dk_match_id, streak_name, streak_label, hth_ind)
);