CREATE TABLE streaks_screener.soccer (
	sofa_match_id int4 NOT NULL,
	dk_match_id int4 NOT NULL,
	league text NULL,
	streak_category text NULL,
	streak_name text NOT NULL,
	streak_value text NULL,
	streak_label text NOT NULL,
	hth_ind bool NOT NULL,
	continued_ind bool NULL,
	home_team text NULL,
	away_team text NULL,
	match_dtime timestamp NULL,
	home_odds int4 NULL,
	draw_odds int4 NULL,
	away_odds int4 NULL,
	home_half_odds int4 NULL,
	draw_half_odds int4 NULL,
	away_half_odds int4 NULL,
	total_goals_under_odds int4 NULL,
	total_goals_line numeric NULL,
	total_goals_over_odds int4 NULL,
	home_first_score_odds int4 NULL,
	no_score_odds int4 NULL,
	away_first_score_odds int4 NULL,
	btts_yes_odds int4 NULL,
	btts_no_odds int4 NULL,
	home_cs_odds int4 NULL,
	away_cs_odds int4 NULL,
	home_no_cs_odds int4 NULL,
	away_no_cs_odds int4 NULL,
	total_corners_under_odds int4 NULL,
	total_corners_line numeric NULL,
	total_corners_over_odds int4 NULL,
	total_cards_under_odds int4 NULL,
	total_cards_line numeric NULL,
	total_cards_over_odds int4 NULL,
	CONSTRAINT soccer_pk PRIMARY KEY (
		sofa_match_id,
		dk_match_id,
		streak_name,
		streak_label,
		hth_ind
	)
);